services:
  book-mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookmanagement
      MYSQL_USER: Tommy
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 20s
      timeout: 20s
      retries: 5
  oauth2-authorization-server:
    image: tommyrabes/spring-authorization-server
    ports:
      - 9000:9000
  spring-boot-webapp:
    image: tommyrabes/spring-boot-webapp
    ports:
      - 8083:8083
    depends_on:
      book-mysql:
        condition: service_healthy
      oauth2-authorization-server:
        condition: service_started