spring:
  jpa:
    mssql:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: dbo
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        show_sql: false
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
      properties:
        databaseAction: drop-and-create
        scriptsAction: drop-and-create
        scriptsCreateSource: metadata
        scriptsDropTarget: mssql-drop-and-create.sql
        scriptsCreateTarget: mssql-drop-and-create.sql