spring:
  jpa:
    mssql:
      hibernate:
        hbm2ddl_auto: validate
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: dbo
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        show_sql: false
        format_sql: false
        use_sql_comments: false
        generate_statistics: false