apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: book-mysql
  name: book-mysql
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: book-mysql
  type: ClusterIP
status:
  loadBalancer: {}
