apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: oauth2-authorization-server
  name: oauth2-authorization-server
spec:
  ports:
  - name: 9000-9000
    nodePort: 31000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: oauth2-authorization-server
  type: NodePort
status:
  loadBalancer: {}
