apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oauth2-authorization-server
  name: oauth2-authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-authorization-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oauth2-authorization-server
    spec:
      containers:
      - image: tommyrabes/spring-authorization-server
        name: spring-authorization-server
        resources: {}
status: {}
