apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-webapp
  name: spring-boot-webapp
spec:
  ports:
  - name: 8083-8083
    nodePort: 31080
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: spring-boot-webapp
  type: NodePort
status:
  loadBalancer: {}
