USE master
GO

CREATE DATABASE BookManagement
GO

CREATE LOGIN BookerLogin WITH PASSWORD = '123456'
GO

USE BookManagement
GO

CREATE USER Booker FOR LOGIN BookerLogin
GO

CREATE ROLE BookerRole AUTHORIZATION Booker
GO

GRANT ALTER TO BookerRole
GRANT CREATE SCHEMA TO BookerRole
GRANT CREATE TABLE TO BookerRole
GRANT CREATE VIEW TO BookerRole
GRANT CREATE SEQUENCE TO BookerRole
GRANT DELETE TO BookerRole
GRANT SELECT TO BookerRole
GRANT UPDATE TO BookerRole
GRANT INSERT TO BookerRole
GO
