USE master
GO

CREATE DATABASE BookManagement
GO

CREATE LOGIN BookerLogin WITH PASSWORD = '123456'
GO

USE BookManagement
GO

CREATE USER Booker FOR LOGIN BookerLogin
GO

CREATE ROLE BookerRole AUTHORIZATION Booker
GO

GRANT ALTER TO BookerRole
GRANT CREATE SCHEMA TO BookerRole
GRANT CREATE TABLE TO BookerRole
GRANT CREATE VIEW TO BookerRole
GRANT CREATE SEQUENCE ON SCHEMA :: dbo TO BookerRole
GRANT REFERENCES TO BookerRole
GRANT DELETE TO BookerRole
GRANT SELECT TO BookerRole
GRANT UPDATE TO BookerRole
GRANT INSERT TO BookerRole

GRANT ALTER TO Booker
GRANT CREATE SCHEMA TO Booker
GRANT CREATE TABLE TO Booker
GRANT CREATE VIEW TO Booker
GRANT CREATE SEQUENCE ON SCHEMA :: dbo TO Booker
GRANT REFERENCES TO Booker
GRANT DELETE TO Booker
GRANT SELECT TO Booker
GRANT UPDATE TO Booker
GRANT INSERT TO Booker
GO
